all: moses-scripts subword-nmt sacreBLEU

moses-scripts:
	git clone https://github.com/mozilla/moses-scripts
subword-nmt:
	git clone https://github.com/mozilla/subword-nmt
sacreBLEU:
	git clone https://github.com/mozilla/sacreBLEU -b master
